# Generated by Django 4.2.7 on 2023-11-04 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectScoreBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=100)),
                ('team_a', models.CharField(max_length=50)),
                ('team_b', models.CharField(max_length=50)),
                ('exact_score', models.CharField(max_length=10)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DailySureTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sport', models.CharField(max_length=50)),
                ('matches', models.TextField()),
                ('prediction', models.TextField()),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('provider', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Daily Sure Tips',
            },
        ),
        migrations.CreateModel(
            name='FixedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('teams', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FixedVIPBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=255)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BetBlitz.fixedmatch')),
            ],
        ),
        migrations.CreateModel(
            name='FreeBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GameMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('league', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('odds_home_team', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odds_away_team', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='HTFTOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('HH', 'Home team wins in first half and full-time'), ('HD', 'Home team wins in first half, match ends in draw'), ('HA', 'Home team wins in first half, away team wins at full-time'), ('DH', 'Draw in first half, home team wins at full-time'), ('DD', 'Draw in first half and full-time'), ('DA', 'Draw in first half, away team wins at full-time'), ('AH', 'Away team wins in first half, home team wins at full-time'), ('AD', 'Away team wins in first half, match ends in draw'), ('AA', 'Away team wins in first half and full-time')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=100)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultiBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bettor', models.CharField(max_length=100)),
                ('total_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('matches', models.ManyToManyField(related_name='multi_bets', to='BetBlitz.match')),
            ],
        ),
        migrations.CreateModel(
            name='OverUnderBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(help_text='Name of the game or event', max_length=100)),
                ('total_value', models.DecimalField(decimal_places=2, help_text='The predefined total value', max_digits=5)),
                ('bet_type', models.CharField(choices=[('Over', 'Over'), ('Under', 'Under')], help_text='Bet type (Over or Under)', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Over/Under Bets',
            },
        ),
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HT_FT_Tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ht_ft_tip_vip', to='BetBlitz.htftoutcome')),
                ('correct_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_score_vip', to='BetBlitz.correctscorebet')),
                ('fixed_vip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_vip', to='BetBlitz.fixedvipbet')),
                ('mixed_vip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mixed_vip', to='BetBlitz.multibet')),
                ('multi_10_plus_odd_vip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multi_10_plus_odd_vip', to='BetBlitz.multibet')),
                ('multi_50_plus_odd_vip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multi_50_plus_odd_vip', to='BetBlitz.multibet')),
                ('single_vip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_vip', to='BetBlitz.fixedvipbet')),
                ('special_vip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_vip', to='BetBlitz.multibet')),
            ],
        ),
        migrations.CreateModel(
            name='Free',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basketball', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basketball', to='BetBlitz.gamematch')),
                ('FootballTips', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='football_tips_free', to='BetBlitz.dailysuretips')),
                ('Tennis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tennis_free', to='BetBlitz.gamematch')),
                ('bonus_surprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_surprise_free', to='BetBlitz.freebet')),
                ('daily_sure_tips', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_sure_tips', to='BetBlitz.dailysuretips')),
                ('over_under', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='over_under', to='BetBlitz.overunderbet')),
                ('single_tips', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='single_tips_free', to='BetBlitz.dailysuretips')),
            ],
        ),
        migrations.CreateModel(
            name='bestOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_vip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_vip', to='BetBlitz.fixedvipbet')),
                ('starter_vip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BetBlitz.fixedvipbet')),
            ],
        ),
    ]
