# Generated by Django 4.2.7 on 2023-11-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BetBlitz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free',
            name='Basketball',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basketball', to='BetBlitz.gamematch'),
        ),
        migrations.AlterField(
            model_name='free',
            name='daily_sure_tips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_sure_tips', to='BetBlitz.dailysuretips'),
        ),
        migrations.AlterField(
            model_name='free',
            name='over_under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='over_under', to='BetBlitz.overunderbet'),
        ),
    ]
