# Generated by Django 4.2.7 on 2023-11-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BetBlitz', '0002_alter_free_basketball_alter_free_daily_sure_tips_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctscorebet',
            name='bet_amount',
        ),
    ]
