# Generated by Django 4.2.7 on 2023-11-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BetBlitz', '0003_remove_correctscorebet_bet_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multibet',
            name='bet_amount',
        ),
    ]
